Repository Wedit-project/Server, pull requests merged in 2025-01, with the labels that each got.

#8 [feat] bankAccounts, decisions, comments 엔티티 설계
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/BankAccounts.java
  src/main/java/com/wedit/weditapp/domain/comments/domain/Comments.java
  src/main/java/com/wedit/weditapp/domain/decisions/domain/Decisions.java
  src/main/java/com/wedit/weditapp/domain/shared/AccountSide.java
Labels: feat

#10 [feat] CI/CD 구현
  .github/workflows/dev.yml
  Dockerfile
  src/main/java/com/wedit/weditapp/domain/shared/S3Service.java
  src/main/java/com/wedit/weditapp/global/config/AwsConfig.java
Labels: feat, 동구

#12 [fix] api title수정
  src/main/java/com/wedit/weditapp/global/config/swagger/SwaggerConfig.java
Labels: fix, 동구

#14 [feat] 필수 정보 등록 api
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDTO.java
  src/main/java/com/wedit/weditapp/domain/shared/Theme.java
Labels: feat, 위즈

#13 [feat] BankAccountsDTO, CommentDTO, DecisionDTO 구현
  src/main/java/com/wedit/weditapp/domain/comments/dto/request/CommentCreateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/response/CommentResponseDTO.java
  src/main/java/com/wedit/weditapp/domain/decisions/dto/request/DecisionCreateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/decisions/dto/response/DecisionResponseDTO.java
Labels: feat, 환이

#16 [feat] 임시 로그인 기능 구현
  src/main/java/com/wedit/weditapp/domain/member/controller/MemberController.java
  src/main/java/com/wedit/weditapp/domain/member/domain/Member.java
  src/main/java/com/wedit/weditapp/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/wedit/weditapp/domain/member/dto/LoginRequestDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/MemberRequestDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/MemberResponseDto.java
  src/main/java/com/wedit/weditapp/domain/member/service/MemberService.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
  src/main/java/com/wedit/weditapp/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/security/jwt/JwtProvider.java
Labels: feat, 동동

#22 [fix] jwt yml 파일 설정
  .github/workflows/dev.yml
  Dockerfile
Labels: fix, 동구

#26 [feat] Oauth.yml 파일 추가
  .github/workflows/dev.yml
  Dockerfile
Labels: feat, 동구

#19 [feat] 필수 정보 등록 API
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/BankAccounts.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/dto/BankAccountDTO.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/Image.java
  src/main/java/com/wedit/weditapp/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/wedit/weditapp/domain/image/service/ImageService.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/repository/InvitationRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDTO.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDTO.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/domain/shared/Theme.java
Labels: feat, 위즈

#20 [feat] OAuth2 소셜 로그인 구현
  src/main/java/com/wedit/weditapp/domain/member/controller/MemberController.java
  src/main/java/com/wedit/weditapp/domain/member/domain/Member.java
  src/main/java/com/wedit/weditapp/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/wedit/weditapp/domain/member/dto/LoginRequestDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/response/TokenResponseDto.java
  src/main/java/com/wedit/weditapp/domain/member/service/MemberService.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/domain/CustomOAuth2User.java
  src/main/java/com/wedit/weditapp/global/auth/login/dto/OAuthAttributes.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/service/CustomOAuth2UserService.java
  src/main/java/com/wedit/weditapp/global/auth/login/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/wedit/weditapp/global/auth/login/userInfo/OAuth2UserInfo.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
  src/main/java/com/wedit/weditapp/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/security/jwt/JwtProvider.java
Labels: feat, 동동

#24 [feat] 특정 청첩장의 방명록 조회 API 구현
  .gitignore
  src/main/java/com/wedit/weditapp/domain/comments/controller/CommentController.java
  src/main/java/com/wedit/weditapp/domain/comments/domain/Comments.java
  src/main/java/com/wedit/weditapp/domain/comments/domain/repository/CommentRepository.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/response/CommentResponseDTO.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/response/PagedCommentResponseDTO.java
  src/main/java/com/wedit/weditapp/domain/comments/service/CommentService.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
Labels: feat, 환이

#34 [feat] 청첩장 조회 API
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/dto/BankAccountDto.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/wedit/weditapp/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/wedit/weditapp/domain/image/service/ImageService.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
Labels: feat, 위즈

#32 [feat] 특정 청첩장에 방명록 등록 API 구현
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/BankAccount.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/dto/BankAccountDto.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/comments/controller/CommentController.java
  src/main/java/com/wedit/weditapp/domain/comments/domain/Comment.java
  src/main/java/com/wedit/weditapp/domain/comments/domain/repository/CommentRepository.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/request/CommentCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/response/CommentResponseDto.java
  src/main/java/com/wedit/weditapp/domain/comments/dto/response/PagedCommentResponseDto.java
  src/main/java/com/wedit/weditapp/domain/comments/service/CommentService.java
  src/main/java/com/wedit/weditapp/domain/decisions/controller/DecisionController.java
  src/main/java/com/wedit/weditapp/domain/decisions/domain/Decision.java
  src/main/java/com/wedit/weditapp/domain/decisions/domain/repository/DecisionRepository.java
  src/main/java/com/wedit/weditapp/domain/decisions/dto/request/DecisionCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/decisions/dto/response/CountResponseDto.java
  src/main/java/com/wedit/weditapp/domain/decisions/dto/response/DecisionResponseDto.java
  src/main/java/com/wedit/weditapp/domain/decisions/service/DecisionService.java
  src/main/java/com/wedit/weditapp/domain/shared/DecisionSide.java
Labels: feat, 환이

#42 [feat] URL 생성 API
  src/main/java/com/wedit/weditapp/domain/bankAccounts/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/Image.java
  src/main/java/com/wedit/weditapp/domain/image/service/ImageService.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: feat, 위즈

#40 [feat] 특정 청첩장에 참석의사 등록 API 구현
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/BankAccount.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/comment/controller/CommentController.java
  src/main/java/com/wedit/weditapp/domain/comment/domain/Comment.java
  src/main/java/com/wedit/weditapp/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/wedit/weditapp/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/wedit/weditapp/domain/comment/dto/response/PagedCommentResponseDto.java
  src/main/java/com/wedit/weditapp/domain/comment/service/CommentService.java
  src/main/java/com/wedit/weditapp/domain/decision/controller/DecisionController.java
  src/main/java/com/wedit/weditapp/domain/decision/domain/Decision.java
  src/main/java/com/wedit/weditapp/domain/decision/domain/repository/DecisionRepository.java
  src/main/java/com/wedit/weditapp/domain/decision/dto/request/DecisionCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/decision/dto/response/CountResponseDto.java
  src/main/java/com/wedit/weditapp/domain/decision/dto/response/DecisionResponseDto.java
  src/main/java/com/wedit/weditapp/domain/decision/service/DecisionService.java
  src/main/java/com/wedit/weditapp/domain/decisions/controller/DecisionController.java
  src/main/java/com/wedit/weditapp/domain/decisions/service/DecisionService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
Labels: feat, 환이

#45 [fix] hot fix import문 수정
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: fix, 동구

#46 [feat] 비회원 조회
  src/main/java/com/wedit/weditapp/domain/decision/domain/repository/DecisionRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/repository/InvitationRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: feat, 위즈

#52 [feat] 최종 수정
  src/main/java/com/wedit/weditapp/domain/bankAccounts/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/bankAccounts/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/wedit/weditapp/domain/comment/service/CommentService.java
  src/main/java/com/wedit/weditapp/domain/decision/domain/repository/DecisionRepository.java
  src/main/java/com/wedit/weditapp/domain/decision/service/DecisionService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/wedit/weditapp/domain/image/service/ImageService.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/repository/InvitationRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/error/ErrorCode.java
Labels: refactor, 위즈

#55 [refactor] dto 수정
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDto.java
Labels: refactor, 위즈

#56 [feat] 마이페이지 청첩장 목록 api 구현
  src/main/java/com/wedit/weditapp/domain/invitation/domain/repository/InvitationRepository.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/domain/member/controller/MemberController.java
  src/main/java/com/wedit/weditapp/domain/member/dto/request/MemberRequestDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/wedit/weditapp/domain/member/dto/response/TokenResponseDto.java
  src/main/java/com/wedit/weditapp/domain/member/service/MemberService.java
Labels: feat, refactor, 동동

#61 [fix] 5173번 포트 허용 추가
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#63 [feat] Redis 추가
  src/main/java/com/wedit/weditapp/domain/member/domain/Member.java
  src/main/java/com/wedit/weditapp/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/service/RefreshTokenService.java
  src/main/java/com/wedit/weditapp/global/auth/login/service/TokenManager.java
  src/main/java/com/wedit/weditapp/global/config/RedisConfig.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: feat, 동동

#65 [fix] SecurityConfig 수정
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#68 [fix] 카카오 소셜 로그인 방식 수정
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
Labels: fix, 동동

#69 [fix] OAuth2LoginSuccessHandler 수정
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
Labels: fix, 동동

#73 [refactor] 시간 정보 추가
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: refactor
