Repository Wedit-project/Server, pull requests merged in 2025-02, with the labels that each got.

#74 [feat] 분석 보기 api 구현
  src/main/java/com/wedit/weditapp/WeditappApplication.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/StatisticsDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/scheduler/InvitationCountScheduler.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/domain/member/controller/MemberController.java
  src/main/java/com/wedit/weditapp/domain/shared/S3Service.java
Labels: feat, 동구

#76 [refactor] 카카오 소셜 로그인 최종 로직 확정
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
Labels: refactor, 동동

#58 [fix] Decision, Comment 실패 응답 수정
  src/main/java/com/wedit/weditapp/domain/comment/controller/CommentController.java
  src/main/java/com/wedit/weditapp/domain/comment/service/CommentService.java
  src/main/java/com/wedit/weditapp/domain/decision/controller/DecisionController.java
  src/main/java/com/wedit/weditapp/domain/decision/service/DecisionService.java
Labels: fix, 환이

#78 [feat] redis 도입
  src/main/java/com/wedit/weditapp/domain/member/domain/Member.java
  src/main/java/com/wedit/weditapp/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/service/RefreshTokenService.java
  src/main/java/com/wedit/weditapp/global/config/RedisConfig.java
Labels: feat, 동동

#83 [refactor] access token 전달 방식 변경
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
Labels: refactor, 동동

#85 [fix] 유니크 id 로직 수정
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: fix, 동구

#91 [fix] 스웨거 설정 수정
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
  src/main/java/com/wedit/weditapp/global/config/swagger/SwaggerConfig.java
Labels: fix, 동구

#93 [fix] JwtProvider 수정
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: bug, fix, 동동

#94 [fix] jwtprovider 수정Lax
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
Labels: bug, fix, 동동

#95 [fix] jwtprovider 수정5
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
Labels: bug, fix, 동동

#100 [refactor] https 설정에 의한 코드 리팩터링
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
Labels: fix, refactor, 동동

#101 [fix] jwtprovider 수정2
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
Labels: fix, 동동

#103 [fix] cors 수정
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동구

#105 [fix] #99 SecurityConfig 수정2
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#106 [fix] #99 SecurityConfig 수정3
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#107 [fix] #99 SecurityConfig 수정4
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#108 [fix] #99 SecurityConfig 수정5
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: refactor, 동동

#109 [fix] #99 SecurityConfig 수정6
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#110 [fix] SecurityConfig 수정_OPTIONS 추가
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동동

#111 [fix] SecurityConfig 수정_/my 추가
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: refactor, 동동

#112 [fix] SecurityConfig 수정_OPTIONS 요청 허용 추가
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: bug, 동동

#115 Refactor/#114 청첩장 리스트 dto 수정
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: refactor, 동구

#117 [fix] AuthController exporeCookie 메서드 수정
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
Labels: fix, 동동

#119 [refactor] URL 양식 수정
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: refactor, 동구

#121 [refactor] URL 양식 수정
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: refactor, 동구

#123 [fix] 설정 변경
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: fix, 동구

#128 [feat] redis 연동
  src/main/java/com/wedit/weditapp/domain/member/domain/Member.java
  src/main/java/com/wedit/weditapp/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
  src/main/java/com/wedit/weditapp/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/wedit/weditapp/global/auth/login/service/RefreshTokenService.java
  src/main/java/com/wedit/weditapp/global/config/RedisConfig.java
Labels: feat, 동동

#129 [fix] RedisConfig_RedisTemplate primary 추가
  src/main/java/com/wedit/weditapp/global/config/RedisConfig.java
Labels: fix, 동동

#131 [mod] URL 양식 재수정
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
Labels: refactor, 동구

#132 [refactor] 전체 리팩토링
  src/main/java/com/wedit/weditapp/domain/bankAccount/domain/BankAccount.java
  src/main/java/com/wedit/weditapp/domain/bankAccount/domain/repository/BankAccountRepository.java
  src/main/java/com/wedit/weditapp/domain/bankAccount/dto/BankAccountDto.java
  src/main/java/com/wedit/weditapp/domain/bankAccount/service/BankAccountService.java
  src/main/java/com/wedit/weditapp/domain/comment/controller/CommentController.java
  src/main/java/com/wedit/weditapp/domain/comment/domain/Comment.java
  src/main/java/com/wedit/weditapp/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/wedit/weditapp/domain/comment/service/CommentService.java
  src/main/java/com/wedit/weditapp/domain/decision/domain/repository/DecisionRepository.java
  src/main/java/com/wedit/weditapp/domain/decision/service/DecisionService.java
  src/main/java/com/wedit/weditapp/domain/image/domain/Image.java
  src/main/java/com/wedit/weditapp/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/wedit/weditapp/domain/image/service/ImageService.java
  src/main/java/com/wedit/weditapp/domain/invitation/controller/InvitationController.java
  src/main/java/com/wedit/weditapp/domain/invitation/domain/Invitation.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationCreateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/request/InvitationUpdateRequestDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/dto/response/InvitationResponseDto.java
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/domain/member/controller/MemberController.java
  src/main/java/com/wedit/weditapp/domain/shared/S3Service.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/domain/CustomOAuth2User.java
  src/main/java/com/wedit/weditapp/global/config/swagger/SwaggerConfig.java
  src/main/java/com/wedit/weditapp/global/error/exception/GlobalExceptionHandler.java
Labels: chore, 동구

#135 [feat] redis 캐싱 추가
  src/main/java/com/wedit/weditapp/domain/invitation/service/InvitationService.java
  src/main/java/com/wedit/weditapp/global/config/RedisCacheConfig.java
Labels: feat, 동동

#138 [fix] 셋도메인 제거
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
Labels: fix, 동구

#141 [refactor] 도메인 통일
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
  src/main/java/com/wedit/weditapp/global/config/SecurityConfig.java
Labels: refactor, 동구, 동동

#142 [fix] #140 도메인 제거
  src/main/java/com/wedit/weditapp/global/auth/jwt/JwtProvider.java
  src/main/java/com/wedit/weditapp/global/auth/login/controller/AuthController.java
Labels: fix, 동구
